

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
    "username": "thanh",
    "password": "1213"
}
###
PUT http://localhost:5000/api/createprovince HTTP/1.1
content-type: application/json

{
    "userid": "2",
    "name": "sample",
    "addressCode": "23"
}
###
PUT http://localhost:5000/api/createaccount HTTP/1.1
content-type: application/json

{
    "username": "sample2",
    "password": "123456",
    "role": "A2",
    "addressCode": ""
}
###
POST http://localhost:5000/api/opendeclaration HTTP/1.1
content-type: application/json

{
    "addressCode": "2",
    "openDeclaration": "true"
}
###
POST api/checkprogress HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}
###
GET http://localhost:5000/api/citizenlist HTTP/1.1
content-type: application/json

{
    "userid": "3"
}
###
GET http://localhost:5000/api/citizenlistfromprovince HTTP/1.1
content-type: application/json

{
    "userid": "2",
    "province": "37"
}
###
GET http://localhost:5000/api/citizeninfo HTTP/1.1
content-type: application/json

{
    "userid": 2,
    "citizen_id": "1"

}
###
PUT api/inputdata HTTP/1.1
content-type: application/json
{
    "citizenId": "",
}
###
GET api/printform HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}
###
POST api/reportcompletion HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}

// phan tich so lieu 
