

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
    "username": "11",
    "password": "1213"
}
###
PUT http://localhost:5000/api/createarea HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQwNDgxMzgxfQ.2NLJ0dq_1JjJqpymJWTxHHGzOl5tucuzxnF-itUi1jI

{
    
    "addressCode": "1198",
    "name": "sample",
    "password": "1213"
}
###
POST http://localhost:5000/api/opendeclaration HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQwNDgxMzgxfQ.2NLJ0dq_1JjJqpymJWTxHHGzOl5tucuzxnF-itUi1jI

{
    
    "addressCode": "1123",
    "time_begin": "2022-01-01",
    "time_end": "2022-03-04"
}
###
GET http://localhost:5000/api/getchildarea HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQwNDgxMzgxfQ.2NLJ0dq_1JjJqpymJWTxHHGzOl5tucuzxnF-itUi1jI

{
    "addressCode": "79"
}
###
POST http://localhost:5000/api/getareadata HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQwNDgxMzgxfQ.2NLJ0dq_1JjJqpymJWTxHHGzOl5tucuzxnF-itUi1jI

{
    "addressCode": ""
}
###
PUT http://localhost:5000/api/createaccount HTTP/1.1
content-type: application/json

{
    "username": "b",
    "password": "123456",
    "role": "A2",
    "addressCode": ""
}
###
POST http://localhost:5000/api/opendeclaration HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQwNDgxMzgxfQ.2NLJ0dq_1JjJqpymJWTxHHGzOl5tucuzxnF-itUi1jI

{
    "addressCode": "1123",
    "time_begin": "2022-01-01",
    "time_end": "2022-03-04"
}
###
POST api/checkprogress HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}
###
GET api/citizenlist HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}
###
GET api/citizeninfo HTTP/1.1
content-type: application/json
{
    "citizenId": "",
}
###
PUT api/inputdata HTTP/1.1
content-type: application/json
{
    "citizenId": "",
}
###
GET api/printform HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}
###
POST api/reportcompletion HTTP/1.1
content-type: application/json
{
    "addressCode": "",
}
###
POST http://localhost:5000/api/addData HTTP/1.1
content-type: application/json

{
    "id_citizen": "1",
    "quiz_id": "1",
    "answer": "Nguyen Thi B"
}
###
PUT http://localhost:5000/api/editdata HTTP/1.1
content-type: application/json

{
    "id_citizen": "2",
    "quiz_id": "1",
    "answer": "A"
}
###
DELETE http://localhost:5000/api/deldata HTTP/1.1
content-type: application/json

{
    "id": "5"
}
###
PUT http://localhost:5000/api/edituser HTTP/1.1
content-type: application/json

{
    "id": "3",
    "username": "Phường Phúc Xá",
    "password": "1213",
    "role": "A3",
    "address_code": "1212"
}
###
DELETE http://localhost:5000/api/deluser HTTP/1.1
content-type: application/json

{
    "id": "2"
}


// phan tich so lieu 
###
POST http://localhost:5000/api/citizennumber HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQwNDgxMzgxfQ.2NLJ0dq_1JjJqpymJWTxHHGzOl5tucuzxnF-itUi1jI

{
    
    "addressCode": "11"
}
###